set(CMAKE_SYSTEM_NAME Linux)
set(ENV linux)
set(ENV_KERNEL linux)
set(WINDOW_SYSTEM x11)
if(NOT PACK_DYN_RELOCS)
	set(PACK_DYN_RELOCS relr)
endif()

string(APPEND CFLAGS_COMMON " -D_GNU_SOURCE")
string(APPEND LDFLAGS " -lm -fuse-ld=mold \
-Wl,-O3,--gc-sections,--as-needed,--icf=all,--exclude-libs=ALL,--pack-dyn-relocs=${PACK_DYN_RELOCS}")

if(CMAKE_CXX_COMPILER_ID STREQUAL Clang)
	if(NOT ENV{CXX})
		set(CMAKE_C_COMPILER clang)
		set(CMAKE_CXX_COMPILER clang++)
	endif()
	include("${CMAKE_CURRENT_LIST_DIR}/clang.cmake")
else()
	if(NOT ENV{CXX})
		set(CMAKE_C_COMPILER ${CTARGET}-gcc-15)
		set(CMAKE_CXX_COMPILER ${CTARGET}-g++-15)
		set(CMAKE_AR ${CTARGET}-gcc-ar)
		set(CMAKE_RANLIB ${CTARGET}-gcc-ranlib)
		set(CMAKE_STRIP ${CTARGET}-strip)
		set(CMAKE_OBJDUMP ${CTARGET}-objdump)
	endif()
	include("${CMAKE_CURRENT_LIST_DIR}/gcc.cmake")
endif()
