set(CMAKE_SYSTEM_NAME Linux)
set(ENV linux)
set(ENV_KERNEL linux)
set(WINDOW_SYSTEM x11)

string(APPEND CFLAGS_COMMON " -D_GNU_SOURCE")
string(APPEND LDFLAGS " -lm -Wl,-O3,--gc-sections,--as-needed,--icf=all -fuse-ld=mold")

if(CMAKE_CXX_COMPILER_ID STREQUAL Clang)
	if(NOT ENV{CXX})
		set(CMAKE_C_COMPILER clang)
		set(CMAKE_CXX_COMPILER clang++)
	endif()
	include("${CMAKE_CURRENT_LIST_DIR}/clang.cmake")
else()
	if(NOT ENV{CXX})
		set(CMAKE_C_COMPILER ${CHOST}-gcc-15)
		set(CMAKE_CXX_COMPILER ${CHOST}-g++-15)
		set(CMAKE_AR ${CHOST}-gcc-ar)
		set(CMAKE_RANLIB ${CHOST}-gcc-ranlib)
		set(CMAKE_STRIP ${CHOST}-strip)
		set(CMAKE_OBJDUMP ${CHOST}-objdump)
	endif()
	include("${CMAKE_CURRENT_LIST_DIR}/gcc.cmake")
endif()
